version: '3'

networks:
  yasmine:

services:
  api:
    build:
      context: ""
      dockerfile: .docker/api/Dockerfile
    container_name: api
    ports:
      - "80:80"
    volumes:
      - .docker/api/api.conf:/etc/nginx/conf.d/default.conf
      - ./kbs-nerdygadgets:/var/www/app
    networks:
      - yasmine
    depends_on:
      - "php"
  php:
    build:
      context: ""
      dockerfile: .docker/php/Dockerfile
    container_name: php
    ports:
      - "9000:9000"
    volumes:
      - ./kbs-nerdygadgets:/var/www/app
    links:
      - db:db
    networks:
      - yasmine
  db:
    image: mariadb
    container_name: db
    restart: unless-stopped
    tty: true
    ports:
      - "3309:3306"
    environment:
      MYSQL_DATABASE: nerdygadgets
      MYSQL_ROOT_PASSWORD: root
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - yasmine
  phpmyadmin:
    build:
      context: ""
      dockerfile: .docker/phpmyadmin/Dockerfile
    container_name: phpmyadmin
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    restart: always
    ports:
      - 8989:80
    links:
      - db:db
    networks:
      - yasmine
    depends_on:
      - "db"
volumes:
  dbdata:
    driver: local













